In [11]:
l1 = [1,2,5,6,8,9]
l2 = [3,5,8,9,0,6]

In [12]:
l1+l2

[1, 2, 5, 6, 8, 9, 3, 5, 8, 9, 0, 6]

In [13]:
sum_l = []
for i,j in zip(l1,l2):
  sum_l.append(i+j)
print(sum_l)


[4, 7, 13, 15, 8, 15]


In [14]:
l2 = []
for i in l1:
  l2.append(i+10)
l2

[11, 12, 15, 16, 18, 19]

In [15]:
import numpy as np

In [16]:
my_list= [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [17]:
arr1 = np.array(l1)
arr2 = np.array(l2)

In [18]:
type(arr1)

numpy.ndarray

In [19]:
arr1+arr2

array([12, 14, 20, 22, 26, 28])

In [20]:
arr1+10

array([11, 12, 15, 16, 18, 19])

In [21]:
arr1.ndim #dimension of an array

1

In [22]:
arr1.shape

(6,)

In [23]:
arr1.dtype

dtype('int64')

In [24]:
arr3 = np.array([1,3.4,6,8,'a'])

In [25]:
arr3

array(['1', '3.4', '6', '8', 'a'], dtype='<U32')

In [26]:
#Arrays are homogeneous

In [27]:
arr4 = np.array([[1,2,3],[4,6,7],[2,8,9]])

In [28]:
arr4

array([[1, 2, 3],
       [4, 6, 7],
       [2, 8, 9]])

In [29]:
arr4.size

9

In [30]:
arr4.ndim

2

In [31]:
arr4.shape

(3, 3)

In [32]:
print(list(range(5,10)))

[5, 6, 7, 8, 9]


In [33]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [ ]:
arr5 = np.arange(10,100,10)

In [ ]:
arr5

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr5.size

9

In [ ]:
arr6 = np.arange(3,21)

In [ ]:
arr6

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [ ]:
arr6.reshape(3,6)

array([[ 3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20]])

In [ ]:
arr6.reshape(6,3)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [ ]:
arr6.reshape(9,2)

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [ ]:
# arr6.reshape(3,3)

In [ ]:
arr6 = arr6.reshape(6,3)

In [ ]:
arr6

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [ ]:
arr5=np.arange(3,21)
arr5

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [ ]:
arr5 = arr5.reshape(6,3)

In [ ]:
arr5

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [34]:
import numpy as np

In [35]:
L = range(1000)
%timeit nums = [i**2 for i in L]

299 µs ± 7.17 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [36]:
nums = np.arange(1000)
%timeit nums**2

1.45 µs ± 348 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [37]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
x = np.array(range(1,100))
my_std = np.sqrt(np.sum((x-np.mean(x))**2)/x.size)
print(my_std)
print(np.std(x))

28.577380332470412
28.577380332470412


In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
z = np.diag([1,2,3,4])


In [ ]:
np.diag(z)

array([1, 2, 3, 4])

In [ ]:
d = np.random.random(3)
d

array([0.38256232, 0.3567122 , 0.38145727])

In [ ]:
np.random.randn(4)

array([ 1.02778777,  1.09417054, -1.35368848,  1.29330701])

In [ ]:
np.random.randint(0, 20, 3)

array([ 7,  6, 10])

In [48]:
a = np.arange(10)

In [49]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a = np.arange(10, dtype=np.float64)

In [ ]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.array([1+3j]).dtype

dtype('complex128')

In [ ]:
np.array([True, False, True]).dtype

dtype('bool')

In [ ]:
np.array(["Ram", "Hello"])

array(['Ram', 'Hello'], dtype='<U5')

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[3]=10

In [ ]:
a

array([ 0,  1,  2, 10,  4,  5,  6,  7,  8,  9])

In [50]:
a = np.arange(10)
a
# 9,7,5,3,1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a[1::2][::-1][::-1]

array([1, 3, 5, 7, 9])

In [ ]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a, b)

True

In [ ]:
c = a[::2].copy()

In [ ]:
np.shares_memory(a, c)

False

In [ ]:
a = np.zeros((4, 4))
b = np.ones((4, 4))
print(a)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
c = np.vstack((a, b))
c.shape

(8, 4)

In [ ]:
d = np.hstack((a, b))
d.shape
d

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [ ]:
np.concatenate([a,b], axis=1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [ ]:
array1 = np.array([1,2,3])

In [ ]:
array1.shape

(3,)

In [ ]:
array1.T.shape

(3,)

In [ ]:
a = np.arange(4)
b = a.T
np.dot(a, b)

14

In [57]:
import pandas as pd

In [58]:
weather_data = [("1/1/2024", 32, 6, "Rain"),
                ("2/11/2024", 35, 7, "Sunny")]

In [59]:
df = pd.DataFrame(weather_data,\
                  columns=["date", "temperature", "wind" ,"climate"])

In [60]:
df

date  temperature  wind climate
0   1/1/2024           32     6    Rain
1  2/11/2024           35     7   Sunny

In [104]:
df = pd.read_csv("auto-mpg.csv")

In [106]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [62]:
df.shape

(398, 9)

In [63]:
df.head(2)

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320

In [67]:
df.columns.tolist()

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'model year',
 'origin',
 'car name']

In [68]:
df[["mpg", "car name"]]

mpg                   car name
0    18.0  chevrolet chevelle malibu
1    15.0          buick skylark 320
2    18.0         plymouth satellite
3    16.0              amc rebel sst
4    17.0                ford torino
..    ...                        ...
393  27.0            ford mustang gl
394  44.0                  vw pickup
395  32.0              dodge rampage
396  28.0                ford ranger
397  31.0                 chevy s-10

[398 rows x 2 columns]

In [ ]:
df[df.mpg == df["mpg"].min()]["car name"]

28    hi 1200d
Name: car name, dtype: object

In [71]:
new_df = df[["car name", "weight"]]
new_df_2 = df[["weight", "car name"]]

In [72]:
new_df.head(1)

car name  weight
0  chevrolet chevelle malibu    3504

In [73]:
new_df_2.head(1)

weight                   car name
0    3504  chevrolet chevelle malibu

In [ ]:
new_df.to_excel("output.xlsx", sheet_name="sheet1")

In [69]:
df.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB


In [ ]:
g = df.groupby("model year")

In [78]:
df.shape

(398, 9)

In [80]:
df_sample = df.sample(frac=0.2)

In [81]:
df_sample.shape

(80, 9)

In [83]:
g = df.groupby("model year")

In [84]:
print(g)

In [ ]:
g.max()

mpg  cylinders  displacement horsepower  weight  acceleration  \
model year                                                                   
73          22.0          8         429.0         94    4952          16.5   
75          24.0          4         140.0         97    2639          17.0   
76          32.0          4          85.0         70    1990          17.0   
77          21.5          4         121.0        110    2600          12.8   
79          27.4          4         121.0         80    2670          15.0   
80          23.6          4         140.0          ?    2905          14.3   
81          34.1          4          91.0         68    1985          16.0   
82          25.0          6         181.0        110    2945          16.4   

            origin                  car name  
model year                                    
73               3  mercury marquis brougham  
75               3                ford pinto  
76               3              datsun b-210  
77               2                  bmw 320i  
79               1             amc spirit dl  
80               1        ford mustang cobra  
81               3               mazda glc 4  
82               1     buick century limited

In [ ]:
for x, model_df in g:
  print(x)
  print(model_df)

73
      mpg  cylinders  displacement horsepower  weight  acceleration  \
90   12.0          8         429.0        198    4952          11.5   
110  22.0          4         108.0         94    2379          16.5   

     model year  origin                  car name  
90           73       1  mercury marquis brougham  
110          73       3                datsun 610  
75
      mpg  cylinders  displacement horsepower  weight  acceleration  \
168  23.0          4         140.0         83    2639          17.0   
173  24.0          4         119.0         97    2545          17.0   

     model year  origin    car name  
168          75       1  ford pinto  
173          75       3  datsun 710  
76
      mpg  cylinders  displacement horsepower  weight  acceleration  \
204  32.0          4          85.0         70    1990          17.0   

     model year  origin      car name  
204          76       3  datsun b-210  
77
      mpg  cylinders  displacement horsepower  weight  acceleration

In [ ]:
df.describe()

mpg  cylinders  displacement       weight  acceleration  \
count  10.000000  10.000000     10.000000    10.000000     10.000000   
mean   24.460000   4.600000    153.500000  2761.000000     15.350000   
std     6.072378   1.349897    100.549877   836.218738      1.931177   
min    12.000000   4.000000     85.000000  1985.000000     11.500000   
25%    22.250000   4.000000    110.750000  2420.500000     14.475000   
50%    23.800000   4.000000    121.000000  2619.500000     16.200000   
75%    26.800000   4.000000    140.000000  2846.250000     16.875000   
max    34.100000   8.000000    429.000000  4952.000000     17.000000   

       model year     origin  
count   10.000000  10.000000  
mean    77.100000   1.900000  
std      3.247221   0.994429  
min     73.000000   1.000000  
25%     75.000000   1.000000  
50%     76.500000   1.500000  
75%     79.750000   3.000000  
max     82.000000   3.000000

In [85]:
us_weather = pd.DataFrame({
    "city": ["newyork", "chicago", "seatle"],
    "temperature": [21, 14, 35],
    "humidity": [68, 65, 75],
})

In [86]:
us_weather

city  temperature  humidity
0  newyork           21        68
1  chicago           14        65
2   seatle           35        75

In [87]:
india_weather = pd.DataFrame({
    "city": ["mumbai", "delhi", "banglore"],
    "temperature": [32, 21, 35],
    "humidity": [60, 75, 78],
})

In [88]:
india_weather

city  temperature  humidity
0    mumbai           32        60
1     delhi           21        75
2  banglore           35        78

In [89]:
weather_us_india = pd.concat([india_weather, us_weather],\
                             ignore_index=True)

In [90]:
weather_us_india

city  temperature  humidity
0    mumbai           32        60
1     delhi           21        75
2  banglore           35        78
3   newyork           21        68
4   chicago           14        65
5    seatle           35        75

In [91]:
weather_us_india["temperature"]<30

0    False
1     True
2    False
3     True
4     True
5    False
Name: temperature, dtype: bool

In [ ]:
weather_us_india[weather_us_india["temperature"]<30]

city  temperature  humidity
3  newyork           21        68
4  chicago           14        65

In [ ]:
pd.concat([us_weather, india_weather], axis=1)

city  temperature  humidity      city  temperature  humidity
0  newyork           21        68    mumbai           32        60
1  chicago           14        65     delhi           21        75
2   seatle           35        75  banglore           35        78

In [ ]:
pd.merge(india_weather, us_weather, on="temperature")

city_x  temperature  humidity_x   city_y  humidity_y
0     delhi           21          75  newyork          68
1  banglore           35          78   seatle          75

In [93]:
df = pd.DataFrame([1, 2, 3, 4], index = [49, 48, 12, 3])

In [94]:
df

0
49  1
48  2
12  3
3   4

In [97]:
df.loc[49]

0    1
Name: 49, dtype: int64

In [99]:
df.iloc[2]

0    3
Name: 12, dtype: int64

In [100]:
city1 = pd.Series([12, -6, 8, -3], index = ["day1", "day2", "day3", "day4"])

In [101]:
city1

day1    12
day2    -6
day3     8
day4    -3
dtype: int64

In [102]:
city1[city1>2]

day1    12
day3     8
dtype: int64

In [107]:
# city1.isna()
city1[~city1.isna()]

day1    12
day2    -6
day3     8
day4    -3
dtype: int64

In [ ]:
city1*3

day1    36
day2   -18
day3    24
day4    -9
dtype: int64

In [ ]:
df = pd.read_csv("auto-mpg.csv")

In [ ]:
df["car name"].unique()

array(['chevrolet chevelle malibu', 'buick skylark 320',
       'plymouth satellite', 'amc rebel sst', 'ford torino',
       'ford galaxie 500', 'chevrolet impala', 'plymouth fury iii',
       'pontiac catalina', 'amc ambassador dpl', 'dodge challenger se',
       "plymouth 'cuda 340", 'chevrolet monte carlo',
       'buick estate wagon (sw)', 'toyota corona mark ii',
       'plymouth duster', 'amc hornet', 'ford maverick', 'datsun pl510',
       'volkswagen 1131 deluxe sedan', 'peugeot 504', 'audi 100 ls',
       'saab 99e', 'bmw 2002', 'amc gremlin', 'ford f250', 'chevy c20',
       'dodge d200', 'hi 1200d', 'chevrolet vega 2300', 'toyota corona',
       'ford pinto', 'plymouth satellite custom', 'ford torino 500',
       'amc matador', 'pontiac catalina brougham', 'dodge monaco (sw)',
       'ford country squire (sw)', 'pontiac safari (sw)',
       'amc hornet sportabout (sw)', 'chevrolet vega (sw)',
       'pontiac firebird', 'ford mustang', 'mercury capri 2000',
       'opel 1900'

In [ ]:
df["cylinders"].value_counts()

cylinders
4    204
8    103
6     84
3      4
5      3
Name: count, dtype: int64

In [ ]:
df.values

array([[18.0, 8, 307.0, ..., 70, 1, 'chevrolet chevelle malibu'],
       [15.0, 8, 350.0, ..., 70, 1, 'buick skylark 320'],
       [18.0, 8, 318.0, ..., 70, 1, 'plymouth satellite'],
       ...,
       [32.0, 4, 135.0, ..., 82, 1, 'dodge rampage'],
       [28.0, 4, 120.0, ..., 82, 1, 'ford ranger'],
       [31.0, 4, 119.0, ..., 82, 1, 'chevy s-10']], dtype=object)

In [ ]:
car_new = df.drop(["origin", "car name"], axis= 1)

In [ ]:
car_new.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year  
count  398.000000  
mean    76.010050  
std      3.697627  
min     70.000000  
25%     73.000000  
50%     76.000000  
75%     79.000000  
max     82.000000